(executable
 (name echo_server)
 (public_name grpc-direct-load-balanced-server)
 (package grpc-direct)
 (libraries grpc-direct eio eio_main unix))

(executable
 (name lb_client)
 (public_name grpc-direct-load-balanced-client)
 (package grpc-direct)
 (libraries grpc-direct grpc-direct-core eio eio_main))
