(** Example gRPC Client for the Greeter service.

    Run with: dune exec examples/greeter/greeter_client.exe

    This demonstrates:
    - Creating a gRPC client with grpc-direct
    - Making unary RPC calls
    - Handling responses and errors
*)

(** Simple request/response types (in real app, generated by ocaml-protoc) *)
module HelloRequest = struct
  type t = { name : string }

  let to_bytes t = t.name
end

module HelloReply = struct
  type t = { message : string }

  let of_bytes bytes = { message = bytes }
end

let () =
  Eio_main.run
  @@ fun env ->
  Eio.Switch.run
  @@ fun sw ->
  (* Connect to the server *)
  let client = Grpc_eio.Client.connect ~sw ~env "http://127.0.0.1:50051" in
  Printf.printf "📡 Connected to gRPC server\n%!";
  (* Make an RPC call *)
  let request = HelloRequest.{ name = "World" } in
  let request_bytes = HelloRequest.to_bytes request in
  Printf.printf "📤 Sending request: name=%s\n%!" request.name;
  match
    Grpc_eio.Client.call_unary
      ~sw
      ~env
      client
      ~service:"helloworld.Greeter"
      ~method_:"SayHello"
      ~request:request_bytes
  with
  | Ok response_bytes ->
    let response = HelloReply.of_bytes response_bytes in
    Printf.printf "📥 Received response: %s\n%!" response.message
  | Error status -> Printf.printf "❌ Error: %s\n%!" (Grpc_core.Status.to_string status)
;;
